#!/bin/sh /etc/rc.common

START=71
APP=meshntpd
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

start() {
    service_start /usr/local/bin/meshntpd.sh
}

stop() {
    service_stop /usr/local/bin/meshntpd.sh
    killall ntpd
}
